server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: 123456

mybatis:
  mapperLocations: classpath:com.tedu.blog.mapper/*.xml

logging:
  level:
    com.tedu.blog.mapper: debug
  file:
    path: ./logs

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql